/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.int_watch.conf
 */
#ifndef GUYCOLE_H
#define GUYCOLE_H

/* function declarations */
void init_guyCole(void);

#endif /* GUYCOLE_H */
