/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef GUYCOLE_H
#define GUYCOLE_H

/* function declarations */
void init_guyCole(void);
Netsnmp_Node_Handler handle_gcSimpleInteger;
Netsnmp_Node_Handler handle_gcSimpleString;

#endif /* GUYCOLE_H */
